package constants

// 告警 alarmCode 常量
const (
	// ALARM_EVENT_REBOOT 事件-网元重启
	ALARM_EVENT_REBOOT = 9000
	// ALARM_STATE_CHECK 告警-状态检查
	ALARM_STATE_CHECK = 10000
	// ALARM_RAM_CPU_CHECK 告警-内存/CPU/磁盘检查
	ALARM_CMD_CHECK = 10001
	// ALARM_LICENSE_CHECK 告警-网元License到期检查
	ALARM_LICENSE_CHECK = 10002
)
