// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: nms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	NeType        string                 `protobuf:"bytes,2,opt,name=ne_type,json=neType,proto3" json:"ne_type,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  map[string]string      `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_nms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *ConnectRequest) GetNeType() string {
	if x != nil {
		return x.NeType
	}
	return ""
}

func (x *ConnectRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ConnectRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectRequest) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *ConnectRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_nms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_nms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *DisconnectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_nms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DisconnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        map[string]string      `protobuf:"bytes,4,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_nms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() map[string]string {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_nms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,3,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ConfigData    []byte                 `protobuf:"bytes,4,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_nms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *ConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ConfigRequest) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *ConfigRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfigId      string                 `protobuf:"bytes,3,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ApplyTime     int64                  `protobuf:"varint,4,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_nms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ConfigResponse) GetApplyTime() int64 {
	if x != nil {
		return x.ApplyTime
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,3,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_nms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *GetConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

type SyncConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,3,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	TargetVersion string                 `protobuf:"bytes,4,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConfigRequest) Reset() {
	*x = SyncConfigRequest{}
	mi := &file_nms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigRequest) ProtoMessage() {}

func (x *SyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigRequest.ProtoReflect.Descriptor instead.
func (*SyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{9}
}

func (x *SyncConfigRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *SyncConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *SyncConfigRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type SyncConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ConfigData     []byte                 `protobuf:"bytes,3,opt,name=config_data,json=configData,proto3" json:"config_data,omitempty"`
	CurrentVersion string                 `protobuf:"bytes,4,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncConfigResponse) Reset() {
	*x = SyncConfigResponse{}
	mi := &file_nms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfigResponse) ProtoMessage() {}

func (x *SyncConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfigResponse.ProtoReflect.Descriptor instead.
func (*SyncConfigResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{10}
}

func (x *SyncConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SyncConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncConfigResponse) GetConfigData() []byte {
	if x != nil {
		return x.ConfigData
	}
	return nil
}

func (x *SyncConfigResponse) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MetricsType   string                 `protobuf:"bytes,3,opt,name=metrics_type,json=metricsType,proto3" json:"metrics_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       []*MetricItem          `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_nms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{11}
}

func (x *MetricsRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *MetricsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MetricsRequest) GetMetricsType() string {
	if x != nil {
		return x.MetricsType
	}
	return ""
}

func (x *MetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsRequest) GetMetrics() []*MetricItem {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricItem) Reset() {
	*x = MetricItem{}
	mi := &file_nms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricItem) ProtoMessage() {}

func (x *MetricItem) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricItem.ProtoReflect.Descriptor instead.
func (*MetricItem) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{12}
}

func (x *MetricItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetricItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricItem) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_nms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsResponse) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *MetricsResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *MetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Alarm         *Alarm                 `protobuf:"bytes,3,opt,name=alarm,proto3" json:"alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmRequest) Reset() {
	*x = AlarmRequest{}
	mi := &file_nms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRequest) ProtoMessage() {}

func (x *AlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRequest.ProtoReflect.Descriptor instead.
func (*AlarmRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{14}
}

func (x *AlarmRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *AlarmRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AlarmRequest) GetAlarm() *Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

type Alarm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlarmId       string                 `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	AlarmType     string                 `protobuf:"bytes,2,opt,name=alarm_type,json=alarmType,proto3" json:"alarm_type,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Params        map[string]string      `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_nms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{15}
}

func (x *Alarm) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *Alarm) GetAlarmType() string {
	if x != nil {
		return x.AlarmType
	}
	return ""
}

func (x *Alarm) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alarm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alarm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alarm) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Alarm) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Alarm) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Alarm) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type AlarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	AlarmId       string                 `protobuf:"bytes,2,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	Ack           bool                   `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmResponse) Reset() {
	*x = AlarmResponse{}
	mi := &file_nms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmResponse) ProtoMessage() {}

func (x *AlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmResponse.ProtoReflect.Descriptor instead.
func (*AlarmResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{16}
}

func (x *AlarmResponse) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *AlarmResponse) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *AlarmResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AlarmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeId          string                 `protobuf:"bytes,1,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	CommandType   string                 `protobuf:"bytes,4,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_nms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{17}
}

func (x *CommandRequest) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

func (x *CommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *CommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ExecTime      int64                  `protobuf:"varint,4,opt,name=exec_time,json=execTime,proto3" json:"exec_time,omitempty"`
	NeId          string                 `protobuf:"bytes,5,opt,name=ne_id,json=neId,proto3" json:"ne_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_nms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{18}
}

func (x *CommandResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandResponse) GetExecTime() int64 {
	if x != nil {
		return x.ExecTime
	}
	return 0
}

func (x *CommandResponse) GetNeId() string {
	if x != nil {
		return x.NeId
	}
	return ""
}

type BatchCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeIds         []string               `protobuf:"bytes,1,rep,name=ne_ids,json=neIds,proto3" json:"ne_ids,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	CommandType   string                 `protobuf:"bytes,4,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Timeout       int32                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Params        map[string]string      `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCommandRequest) Reset() {
	*x = BatchCommandRequest{}
	mi := &file_nms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCommandRequest) ProtoMessage() {}

func (x *BatchCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCommandRequest.ProtoReflect.Descriptor instead.
func (*BatchCommandRequest) Descriptor() ([]byte, []int) {
	return file_nms_proto_rawDescGZIP(), []int{19}
}

func (x *BatchCommandRequest) GetNeIds() []string {
	if x != nil {
		return x.NeIds
	}
	return nil
}

func (x *BatchCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BatchCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *BatchCommandRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *BatchCommandRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *BatchCommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_nms_proto protoreflect.FileDescriptor

const file_nms_proto_rawDesc = "" +
	"\n" +
	"\tnms.proto\x12\x03nms\"\xde\x02\n" +
	"\x0eConnectRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x17\n" +
	"\ane_type\x18\x02 \x01(\tR\x06neType\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x124\n" +
	"\x05attrs\x18\x05 \x03(\v2\x1e.nms.ConnectRequest.AttrsEntryR\x05attrs\x12I\n" +
	"\fcapabilities\x18\x06 \x03(\v2%.nms.ConnectRequest.CapabilitiesEntryR\fcapabilities\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x0fConnectResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\"_\n" +
	"\x11DisconnectRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"B\n" +
	"\x12DisconnectResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xda\x01\n" +
	"\x10HeartbeatRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x129\n" +
	"\x06status\x18\x04 \x03(\v2!.nms.HeartbeatRequest.StatusEntryR\x06status\x1a9\n" +
	"\vStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x11HeartbeatResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9f\x01\n" +
	"\rConfigRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconfig_type\x18\x03 \x01(\tR\n" +
	"configType\x12\x1f\n" +
	"\vconfig_data\x18\x04 \x01(\fR\n" +
	"configData\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"z\n" +
	"\x0eConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tconfig_id\x18\x03 \x01(\tR\bconfigId\x12\x1d\n" +
	"\n" +
	"apply_time\x18\x04 \x01(\x03R\tapplyTime\"g\n" +
	"\x10GetConfigRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconfig_type\x18\x03 \x01(\tR\n" +
	"configType\"\x8f\x01\n" +
	"\x11SyncConfigRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vconfig_type\x18\x03 \x01(\tR\n" +
	"configType\x12%\n" +
	"\x0etarget_version\x18\x04 \x01(\tR\rtargetVersion\"\x8c\x01\n" +
	"\x12SyncConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vconfig_data\x18\x03 \x01(\fR\n" +
	"configData\x12'\n" +
	"\x0fcurrent_version\x18\x04 \x01(\tR\x0ecurrentVersion\"\xb0\x01\n" +
	"\x0eMetricsRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fmetrics_type\x18\x03 \x01(\tR\vmetricsType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12)\n" +
	"\ametrics\x18\x05 \x03(\v2\x0f.nms.MetricItemR\ametrics\"\xba\x01\n" +
	"\n" +
	"MetricItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x123\n" +
	"\x06labels\x18\x04 \x03(\v2\x1b.nms.MetricItem.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0fMetricsResponse\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"d\n" +
	"\fAlarmRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12 \n" +
	"\x05alarm\x18\x03 \x01(\v2\n" +
	".nms.AlarmR\x05alarm\"\xd0\x02\n" +
	"\x05Alarm\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmId\x12\x1d\n" +
	"\n" +
	"alarm_type\x18\x02 \x01(\tR\talarmType\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x12.\n" +
	"\x06params\x18\t \x03(\v2\x16.nms.Alarm.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\rAlarmResponse\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x19\n" +
	"\balarm_id\x18\x02 \x01(\tR\aalarmId\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\bR\x03ack\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x8f\x02\n" +
	"\x0eCommandRequest\x12\x13\n" +
	"\x05ne_id\x18\x01 \x01(\tR\x04neId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12!\n" +
	"\fcommand_type\x18\x04 \x01(\tR\vcommandType\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x127\n" +
	"\x06params\x18\x06 \x03(\v2\x1f.nms.CommandRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\x0fCommandResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1b\n" +
	"\texec_time\x18\x04 \x01(\x03R\bexecTime\x12\x13\n" +
	"\x05ne_id\x18\x05 \x01(\tR\x04neId\"\x9b\x02\n" +
	"\x13BatchCommandRequest\x12\x15\n" +
	"\x06ne_ids\x18\x01 \x03(\tR\x05neIds\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12!\n" +
	"\fcommand_type\x18\x04 \x01(\tR\vcommandType\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x12<\n" +
	"\x06params\x18\x06 \x03(\v2$.nms.BatchCommandRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf1\x04\n" +
	"\n" +
	"NMSService\x124\n" +
	"\aConnect\x12\x13.nms.ConnectRequest\x1a\x14.nms.ConnectResponse\x12=\n" +
	"\n" +
	"Disconnect\x12\x16.nms.DisconnectRequest\x1a\x17.nms.DisconnectResponse\x12>\n" +
	"\tHeartbeat\x12\x15.nms.HeartbeatRequest\x1a\x16.nms.HeartbeatResponse(\x010\x01\x125\n" +
	"\n" +
	"PushConfig\x12\x12.nms.ConfigRequest\x1a\x13.nms.ConfigResponse\x127\n" +
	"\tGetConfig\x12\x15.nms.GetConfigRequest\x1a\x13.nms.ConfigResponse\x12=\n" +
	"\n" +
	"SyncConfig\x12\x16.nms.SyncConfigRequest\x1a\x17.nms.SyncConfigResponse\x12>\n" +
	"\rReportMetrics\x12\x13.nms.MetricsRequest\x1a\x14.nms.MetricsResponse(\x010\x01\x129\n" +
	"\fReportAlarms\x12\x11.nms.AlarmRequest\x1a\x12.nms.AlarmResponse(\x010\x01\x12;\n" +
	"\x0eExecuteCommand\x12\x13.nms.CommandRequest\x1a\x14.nms.CommandResponse\x12G\n" +
	"\x13BatchExecuteCommand\x12\x18.nms.BatchCommandRequest\x1a\x14.nms.CommandResponse0\x01B'Z%github.com/tsmask/go-oam/nms/proto;pbb\x06proto3"

var (
	file_nms_proto_rawDescOnce sync.Once
	file_nms_proto_rawDescData []byte
)

func file_nms_proto_rawDescGZIP() []byte {
	file_nms_proto_rawDescOnce.Do(func() {
		file_nms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nms_proto_rawDesc), len(file_nms_proto_rawDesc)))
	})
	return file_nms_proto_rawDescData
}

var file_nms_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_nms_proto_goTypes = []any{
	(*ConnectRequest)(nil),      // 0: nms.ConnectRequest
	(*ConnectResponse)(nil),     // 1: nms.ConnectResponse
	(*DisconnectRequest)(nil),   // 2: nms.DisconnectRequest
	(*DisconnectResponse)(nil),  // 3: nms.DisconnectResponse
	(*HeartbeatRequest)(nil),    // 4: nms.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 5: nms.HeartbeatResponse
	(*ConfigRequest)(nil),       // 6: nms.ConfigRequest
	(*ConfigResponse)(nil),      // 7: nms.ConfigResponse
	(*GetConfigRequest)(nil),    // 8: nms.GetConfigRequest
	(*SyncConfigRequest)(nil),   // 9: nms.SyncConfigRequest
	(*SyncConfigResponse)(nil),  // 10: nms.SyncConfigResponse
	(*MetricsRequest)(nil),      // 11: nms.MetricsRequest
	(*MetricItem)(nil),          // 12: nms.MetricItem
	(*MetricsResponse)(nil),     // 13: nms.MetricsResponse
	(*AlarmRequest)(nil),        // 14: nms.AlarmRequest
	(*Alarm)(nil),               // 15: nms.Alarm
	(*AlarmResponse)(nil),       // 16: nms.AlarmResponse
	(*CommandRequest)(nil),      // 17: nms.CommandRequest
	(*CommandResponse)(nil),     // 18: nms.CommandResponse
	(*BatchCommandRequest)(nil), // 19: nms.BatchCommandRequest
	nil,                         // 20: nms.ConnectRequest.AttrsEntry
	nil,                         // 21: nms.ConnectRequest.CapabilitiesEntry
	nil,                         // 22: nms.HeartbeatRequest.StatusEntry
	nil,                         // 23: nms.MetricItem.LabelsEntry
	nil,                         // 24: nms.Alarm.ParamsEntry
	nil,                         // 25: nms.CommandRequest.ParamsEntry
	nil,                         // 26: nms.BatchCommandRequest.ParamsEntry
}
var file_nms_proto_depIdxs = []int32{
	20, // 0: nms.ConnectRequest.attrs:type_name -> nms.ConnectRequest.AttrsEntry
	21, // 1: nms.ConnectRequest.capabilities:type_name -> nms.ConnectRequest.CapabilitiesEntry
	22, // 2: nms.HeartbeatRequest.status:type_name -> nms.HeartbeatRequest.StatusEntry
	12, // 3: nms.MetricsRequest.metrics:type_name -> nms.MetricItem
	23, // 4: nms.MetricItem.labels:type_name -> nms.MetricItem.LabelsEntry
	15, // 5: nms.AlarmRequest.alarm:type_name -> nms.Alarm
	24, // 6: nms.Alarm.params:type_name -> nms.Alarm.ParamsEntry
	25, // 7: nms.CommandRequest.params:type_name -> nms.CommandRequest.ParamsEntry
	26, // 8: nms.BatchCommandRequest.params:type_name -> nms.BatchCommandRequest.ParamsEntry
	0,  // 9: nms.NMSService.Connect:input_type -> nms.ConnectRequest
	2,  // 10: nms.NMSService.Disconnect:input_type -> nms.DisconnectRequest
	4,  // 11: nms.NMSService.Heartbeat:input_type -> nms.HeartbeatRequest
	6,  // 12: nms.NMSService.PushConfig:input_type -> nms.ConfigRequest
	8,  // 13: nms.NMSService.GetConfig:input_type -> nms.GetConfigRequest
	9,  // 14: nms.NMSService.SyncConfig:input_type -> nms.SyncConfigRequest
	11, // 15: nms.NMSService.ReportMetrics:input_type -> nms.MetricsRequest
	14, // 16: nms.NMSService.ReportAlarms:input_type -> nms.AlarmRequest
	17, // 17: nms.NMSService.ExecuteCommand:input_type -> nms.CommandRequest
	19, // 18: nms.NMSService.BatchExecuteCommand:input_type -> nms.BatchCommandRequest
	1,  // 19: nms.NMSService.Connect:output_type -> nms.ConnectResponse
	3,  // 20: nms.NMSService.Disconnect:output_type -> nms.DisconnectResponse
	5,  // 21: nms.NMSService.Heartbeat:output_type -> nms.HeartbeatResponse
	7,  // 22: nms.NMSService.PushConfig:output_type -> nms.ConfigResponse
	7,  // 23: nms.NMSService.GetConfig:output_type -> nms.ConfigResponse
	10, // 24: nms.NMSService.SyncConfig:output_type -> nms.SyncConfigResponse
	13, // 25: nms.NMSService.ReportMetrics:output_type -> nms.MetricsResponse
	16, // 26: nms.NMSService.ReportAlarms:output_type -> nms.AlarmResponse
	18, // 27: nms.NMSService.ExecuteCommand:output_type -> nms.CommandResponse
	18, // 28: nms.NMSService.BatchExecuteCommand:output_type -> nms.CommandResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nms_proto_init() }
func file_nms_proto_init() {
	if File_nms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nms_proto_rawDesc), len(file_nms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nms_proto_goTypes,
		DependencyIndexes: file_nms_proto_depIdxs,
		MessageInfos:      file_nms_proto_msgTypes,
	}.Build()
	File_nms_proto = out.File
	file_nms_proto_goTypes = nil
	file_nms_proto_depIdxs = nil
}
