// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: nms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NMSService_Connect_FullMethodName             = "/nms.NMSService/Connect"
	NMSService_Disconnect_FullMethodName          = "/nms.NMSService/Disconnect"
	NMSService_Heartbeat_FullMethodName           = "/nms.NMSService/Heartbeat"
	NMSService_PushConfig_FullMethodName          = "/nms.NMSService/PushConfig"
	NMSService_GetConfig_FullMethodName           = "/nms.NMSService/GetConfig"
	NMSService_SyncConfig_FullMethodName          = "/nms.NMSService/SyncConfig"
	NMSService_ReportMetrics_FullMethodName       = "/nms.NMSService/ReportMetrics"
	NMSService_ReportAlarms_FullMethodName        = "/nms.NMSService/ReportAlarms"
	NMSService_ExecuteCommand_FullMethodName      = "/nms.NMSService/ExecuteCommand"
	NMSService_BatchExecuteCommand_FullMethodName = "/nms.NMSService/BatchExecuteCommand"
)

// NMSServiceClient is the client API for NMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NMSServiceClient interface {
	// 连接管理
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// 配置管理
	PushConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	SyncConfig(ctx context.Context, in *SyncConfigRequest, opts ...grpc.CallOption) (*SyncConfigResponse, error)
	// 性能管理（流式上报）
	ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricsRequest, MetricsResponse], error)
	// 告警管理（流式上报）
	ReportAlarms(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AlarmRequest, AlarmResponse], error)
	// 命令控制
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	BatchExecuteCommand(ctx context.Context, in *BatchCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResponse], error)
}

type nMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNMSServiceClient(cc grpc.ClientConnInterface) NMSServiceClient {
	return &nMSServiceClient{cc}
}

func (c *nMSServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, NMSService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, NMSService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NMSService_ServiceDesc.Streams[0], NMSService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *nMSServiceClient) PushConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, NMSService_PushConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, NMSService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) SyncConfig(ctx context.Context, in *SyncConfigRequest, opts ...grpc.CallOption) (*SyncConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncConfigResponse)
	err := c.cc.Invoke(ctx, NMSService_SyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) ReportMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricsRequest, MetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NMSService_ServiceDesc.Streams[1], NMSService_ReportMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsRequest, MetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_ReportMetricsClient = grpc.BidiStreamingClient[MetricsRequest, MetricsResponse]

func (c *nMSServiceClient) ReportAlarms(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AlarmRequest, AlarmResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NMSService_ServiceDesc.Streams[2], NMSService_ReportAlarms_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AlarmRequest, AlarmResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_ReportAlarmsClient = grpc.BidiStreamingClient[AlarmRequest, AlarmResponse]

func (c *nMSServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NMSService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nMSServiceClient) BatchExecuteCommand(ctx context.Context, in *BatchCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NMSService_ServiceDesc.Streams[3], NMSService_BatchExecuteCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchCommandRequest, CommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_BatchExecuteCommandClient = grpc.ServerStreamingClient[CommandResponse]

// NMSServiceServer is the server API for NMSService service.
// All implementations must embed UnimplementedNMSServiceServer
// for forward compatibility.
type NMSServiceServer interface {
	// 连接管理
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// 配置管理
	PushConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error)
	SyncConfig(context.Context, *SyncConfigRequest) (*SyncConfigResponse, error)
	// 性能管理（流式上报）
	ReportMetrics(grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]) error
	// 告警管理（流式上报）
	ReportAlarms(grpc.BidiStreamingServer[AlarmRequest, AlarmResponse]) error
	// 命令控制
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	BatchExecuteCommand(*BatchCommandRequest, grpc.ServerStreamingServer[CommandResponse]) error
	mustEmbedUnimplementedNMSServiceServer()
}

// UnimplementedNMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNMSServiceServer struct{}

func (UnimplementedNMSServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNMSServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedNMSServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNMSServiceServer) PushConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushConfig not implemented")
}
func (UnimplementedNMSServiceServer) GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedNMSServiceServer) SyncConfig(context.Context, *SyncConfigRequest) (*SyncConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncConfig not implemented")
}
func (UnimplementedNMSServiceServer) ReportMetrics(grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedNMSServiceServer) ReportAlarms(grpc.BidiStreamingServer[AlarmRequest, AlarmResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportAlarms not implemented")
}
func (UnimplementedNMSServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedNMSServiceServer) BatchExecuteCommand(*BatchCommandRequest, grpc.ServerStreamingServer[CommandResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchExecuteCommand not implemented")
}
func (UnimplementedNMSServiceServer) mustEmbedUnimplementedNMSServiceServer() {}
func (UnimplementedNMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeNMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NMSServiceServer will
// result in compilation errors.
type UnsafeNMSServiceServer interface {
	mustEmbedUnimplementedNMSServiceServer()
}

func RegisterNMSServiceServer(s grpc.ServiceRegistrar, srv NMSServiceServer) {
	// If the following call panics, it indicates UnimplementedNMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NMSService_ServiceDesc, srv)
}

func _NMSService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NMSServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _NMSService_PushConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).PushConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_PushConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).PushConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_SyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).SyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_SyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).SyncConfig(ctx, req.(*SyncConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_ReportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NMSServiceServer).ReportMetrics(&grpc.GenericServerStream[MetricsRequest, MetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_ReportMetricsServer = grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]

func _NMSService_ReportAlarms_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NMSServiceServer).ReportAlarms(&grpc.GenericServerStream[AlarmRequest, AlarmResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_ReportAlarmsServer = grpc.BidiStreamingServer[AlarmRequest, AlarmResponse]

func _NMSService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NMSServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NMSService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NMSServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NMSService_BatchExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NMSServiceServer).BatchExecuteCommand(m, &grpc.GenericServerStream[BatchCommandRequest, CommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NMSService_BatchExecuteCommandServer = grpc.ServerStreamingServer[CommandResponse]

// NMSService_ServiceDesc is the grpc.ServiceDesc for NMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nms.NMSService",
	HandlerType: (*NMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _NMSService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _NMSService_Disconnect_Handler,
		},
		{
			MethodName: "PushConfig",
			Handler:    _NMSService_PushConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _NMSService_GetConfig_Handler,
		},
		{
			MethodName: "SyncConfig",
			Handler:    _NMSService_SyncConfig_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _NMSService_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _NMSService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportMetrics",
			Handler:       _NMSService_ReportMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportAlarms",
			Handler:       _NMSService_ReportAlarms_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BatchExecuteCommand",
			Handler:       _NMSService_BatchExecuteCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nms.proto",
}
